{{- if .Values.deployment.appdynamics.enable }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.deployment.app}}-appd-secret
    namespace: {{ .Values.namespace }}
type: Opaque
stringData:
    access-key: {{ .Values.deployment.appdynamics.APPD_KEY }}
{{- end }}

