apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.deployment.googleServiceAccountEmail}}
  name: {{ .Values.deployment.serviceAccountName}}
  namespace: {{ .Values.namespace}}
  