apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.app}}
  
spec:
  selector:
    app: {{ .Values.deployment.app}}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.deployment.port }}
