spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/phmsDB-local?authSource=admin&readPreference=primary&directConnection=true&ssl=false&retryWrites=true&w=majority
      auto-index-creation: true
  redis:
    host: localhost
    port: 6379

provinces:
  quebec:
    request:
      sender:
        processingCode: D

services:
  internal:
    responseTimeout: 2000
    connectTimeout: 2000
    readTimeout: 2000
    writeTimeout: 2000
    graphql:
      url: https://vph-lwr.banting.lblw.cloud/dev/aggregate
    objectStorage:
      baseUrl: https://vph-lwr.banting.lblw.cloud/dev/objectstorage/
      objectStorePath: vphx/objectstore/{refId}
    rds:
      schedule:
        cron: 0 0/30 * 1/1 * ?
      baseUrl: http://localhost:50001/
      actuator: /actuator/health
      vocabPath: v1/lookup/VOCAB/{vocabType}
    iam:
      clientId: ${sm://projects/vph-phms-lwr/secrets/lwr-b2c-client}
      clientSecret: ${sm://projects/vph-phms-lwr/secrets/lwr-b2c-secret}
      environment: dev
    dps:
      baseUrl: https://vph-lwr.banting.lblw.cloud/dev/dataprotection/
      paths:
        deidentifyBlobPath: deidentify/blob
        reidentifyBlobPath: reidentify/blob
        
rds:
  baseUrl: http://localhost:50001/